#!/usr/bin/env node

// disable @stacks logging, since we need to collect stdout
const stacksCommon = require("@stacks/common");
let stacksConfig = stacksCommon.config;
stacksConfig.logLevel = "none";

const stacksAuth = require("@stacks/auth");
const stacksStorage = require("@stacks/storage");
const stx = require("@stacks/transactions");
const stacksProfile = require("@stacks/profile");
const stacksEncryption = require("@stacks/encryption");

const jwt = require('jsontokens');

const fs = require("node:fs");
const Path = require("node:path");

const UserSession = stacksAuth.UserSession;
const AppConfig = stacksAuth.AppConfig;
const Storage = stacksStorage.Storage;

let DEBUG = true;
const DEFAULT_HUB = "https://hub.blockstack.org"
const DEFAULT_NODE = "http://seed-0.mainnet.stacks.co:20443"

function debug(msg) {
  if (DEBUG) {
    console.error(msg);
  }
}

const BURN_MAINNET = 'SP000000000000000000002Q6VF78';
const BURN_TESTNET = 'ST000000000000000000002AMW42H';

function getBurnAddress(mainnet) {
  if (mainnet) {
    return BURN_MAINNET;
  }
  else {
    return BURN_TESTNET;
  }
}

// argv: string[]: list of arguments to parse
// opts: string: getopt(3)-style short options
// longOpts: object: long option names keyed to short option characters in opts
function getCLIOpts(argv, opts, longOpts) {
  const optsTable = {};
  const remainingArgv = [];
  const argvBuff = argv.slice(0);

  for (let i = 0; i < opts.length; i++) {
    if (opts[i] == ':') {
      continue;
    }
    if (i + 1 < opts.length && opts[i + 1] === ':') {
      optsTable[opts[i]] = null;
    } else {
      optsTable[opts[i]] = false;
    }
  }

  for (const opt of Object.keys(optsTable)) {
    for (let i = 0; i < argvBuff.length; i++) {
      if (argvBuff[i] === null) {
        break;
      }
      if (argvBuff[i] === '--') {
        break;
      }

      const argvOpt = `-${opt}`;
      const longOptName = longOpts[opt] !== undefined ? longOpts[opt] : '';
      const longOpt = `--${longOpts[longOptName]}`;
      if (argvOpt === argvBuff[i] || longOpt === argvBuff[i]) {
        if (optsTable[opt] === false) {
          // boolean switch
          optsTable[opt] = true;
          argvBuff[i] = '';
        } else {
          // argument
          optsTable[opt] = argvBuff[i + 1];
          argvBuff[i] = '';
          argvBuff[i + 1] = '';
        }
      }
    }
  }

  for (let i = 0; i < argvBuff.length; i++) {
    if (argvBuff[i].length > 0) {
      if (argvBuff[i] === '--') {
        continue;
      }
      remainingArgv.push(argvBuff[i]);
    }
  }

  optsTable['_'] = remainingArgv;
  return optsTable;
}

// Print usage for putfiles and exit
function usagePutFiles() {
  console.error(
    `Usage: ${process.argv[1]} putfiles [options] name path [name path...]\n` +
    `Where [options] are:\n` +
    '   -a, --association-token TEXT  Gaia association token JWT\n' +
    `   -h, --hub URL                 Gaia hub write URL. Defaults to ${DEFAULT_HUB}\n` +
    '   -k, --privkey TEXT            (required) Hex-encoded private key. If - is passed, it will be read from stdin.\n' +
    '   -p, --no-encrypt              Do not encrypt the files\n' +
    '   -s, --no-sign                 Do not sign the files.  Requires -p, --no-encrypt.\n' +
    '\n' +
    'Each file at a given `path` will be uploaded as `name` to the Gaia hub.'
  );
  process.exit(1);
}

// Print usage for listfiles and exit
function usageListFiles() {
  console.error(
    `Usage: ${process.argv[1]} listfiles [options]\n` +
    `Where [options] are:\n` +
    '   -a, --association-token TEXT  Gaia association token JWT\n' +
    `   -h, --hub URL                 Gaia hub write URL. Defaults to ${DEFAULT_HUB}` +
    '   -k, --privkey TEXT            (required) Hex-encoded private key. If - is passed, it will be read from stdin.\n'
  );
  process.exit(1);
}

// Print usage for deletefiles and exit
function usageDeleteFiles() {
  console.error(
    `Usage: ${process.argv[1]} deletefiles [options] name [name...] \n` +
    `Where [options] are:\n` +
    '   -a, --association-token TEXT  Gaia association token JWT\n' +
    '   -k, --privkey TEXT            (required) Hex-encoded private key. If - is passed, it will be read from stdin.\n' +
    `   -h, --hub URL                 Gaia hub write URL. Defaults to ${DEFAULT_HUB}`
  );
  process.exit(1);
}

// Print usage for getfiles and exit
function usageGetFiles() {
  console.error(
    `Usage: ${process.argv[1]} getfiles [options] name path [name path...]\n` +
    `Where [options] are:\n` +
    '   -k, --privkey TEXT      Hex-encoded private key. If - is passed, it will be read from stdin.\n' +
    `   -h, --hub URL           Gaia hub write URL. Defaults to ${DEFAULT_HUB}\n` + 
    '   -p, --not-encrypted     File is plaintext, so do not try to decrypt it.\n' +
    '   -q, --quiet             Do not print a report (use with a `path` of -)\n' +
    '   -s, --not-signed        File is not signed, so do not try to verify it.\n' +
    'If `path` is -, then the file is written to stdout. At most one path may be -.'
  );
  process.exit(1);
}

// Print usage for getpubfiles
function usageGetPublicFiles() {
  console.error(
    `Usage: ${process.argv[1]} getpubfiles [options] name path [name path...]\n` +
    `Where [options] are:\n` +
    '   -a, --app-url URL       URL to the application.\n' +
    '   -b, --bns-name NAME     BNS name of the file creator.\n' +
    '   -k, --privkey TEXT      Private key to use to decrypt a file, if needed.\n' +
    `   -n, --node URL          Stacks node RPC to contact. Defaults to ${DEFAULT_NODE}\n` +
    '   -p, --not-encrypted     File is plaintext, so do not try to decrypt it.\n' +
    '   -q, --quiet             Do not print a report (use with a `path` of -)\n' +
    '   -s, --not-signed        File is not signed, so do not try to verify it.\n' +
    '   -t, --testnet           Query against a testnet node.\n' +
    'If `path` is -, then the file is written to stdout. At most one path may be -.'
  );
  process.exit(1);
}

// Print usage for getprofiles
function usageGetProfiles() {
  console.error(
    `Usage: ${process.argv[1]} getprofiles [options] bns_name [bns_name...]\n` +
    `Where [options] are:\n` +
    `   -n, --node URL          Stacks node RPC to contact. Defaults to ${DEFAULT_NODE}\n` +
    '   -t, --testnet           Query against a testnet node.\n'
  );
  process.exit(1);
}

// Print usage for getzonefiles
function usageGetZonefiles() {
  console.error(
    `Usage: ${process.argv[1]} getzonefiles [options] bns_name [bns_name...]\n` +
    `Where [options] are:\n` +
    `   -n, --node URL          Stacks node RPC to contact. Defaults to ${DEFAULT_NODE}\n` +
    '   -r, --raw               Write downloaded zone file data directly to stdout.\n' +
    '   -t, --testnet           Query against a testnet node.\n'
  );
  process.exit(1);
}

// Print usage for decodefile
function usageDecodeFile() {
  console.error(
    `Usage: ${process.argv[1]} decodefile [options] path\n` +
    `Where [options] are:\n` +
    '   -k, --privkey TEXT      Private key to use to decrypt a file, if needed.\n' +
    '   -o, --owner             Owner address of this file. Used for signature verification.\n' +
    '   -p, --not-encrypted     File is plaintext, so do not try to decrypt it.\n' +
    '   -s, --not-signed        File is not signed, so do not try to verify it.\n'
  );
  process.exit(1);
}

// Print subcommand usage
function usageSubcommands() {
  console.error(
    `Usage: ${process.argv[1]} subcommand [options] args...\n` +
    `Where \`subcommand\` is any of the following:\n` +
    `  BNS:\n` +
    `    getprofiles             Look up other users' BNS name info.\n` +
    `    getzonefiles            Look up other users' BNS zonefiles.\n` +
    `\n` +
    `  Gaia:\n` +
    `    getfiles                Download files from your Gaia hub, including private ones.\n` +
    `    getpubfiles             Download public files from another user's Gaia hub.\n` +
    `    listfiles               List files in the Gaia hub.\n` +
    `    putfiles                Upload files to the Gaia hub.\n` +
    `    deletefiles             Delete files in the Gaia hub.\n` +
    `\n` +
    `  Data:\n` +
    `    decodefile              Decode a raw Gaia-stored file.\n` +
    `\n` +
    `  Internal:\n` +
    `    help                    Print this message.\n` +
    `For detailed subcommand usage, run \`${process.argv[1]} help subcommand\``
  );
  process.exit(1);
}

function getPrivateKey(privkey) {
  if (privkey === '-') {
    const privkey = fs.readFileSync(0, { encoding: 'utf8' });
    return privkey.trim();
  }
  else {
    return privkey;
  }
}

function getAddressFromToken(gaiaAuthToken) {
  let gaiaAuthJSON;
  try {
    gaiaAuthJSON = jwt.decodeToken(gaiaAuthToken.slice(2));
  }
  catch (error) {
    console.error(`Failed to decode Gaia authentication token: ${error}`);
    throw new Error("Failed to decode Gaia authentication token");
  }

  let publicKey;
  if (!!gaiaAuthJSON.payload.associationToken) {
    let assocJSON;
    try {
      assocJSON = jwt.decodeToken(gaiaAuthJSON.payload.associationToken.slice(2));
    }
    catch (error) {
      console.error(`Failed to decode Gaia association token: ${error}`);
      throw new Error("Failed to decode Gaia association token");
    }
    publicKey = assocJSON.payload.childToAssociate;
  }
  else {
    publicKey = gaiaAuthJSON.payload.iss;
  }
  return stacksEncryption.publicKeyToAddress(publicKey);
}


// Set up storage.
// Use the given gaiaAuthToken if given.
// If not given, then use the given associationToken
async function makeStorage(privateKey, hubUrl, associationToken, gaiaAuthToken) {
  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  let userData = {
    hubUrl: hubUrl,
  };
  if (!!privateKey) {
    userData.appPrivateKey = privateKey;
  }
  if (!!gaiaAuthToken) {
    const response = await fetch(`${hubUrl}/hub_info`);
    const hubInfo = await response.json();

    const address = getAddressFromToken(gaiaAuthToken);
    const hubConfig = {
      address: address,
      url_prefix: hubInfo.read_url_prefix,
      token: gaiaAuthToken,
      max_file_upload_size_megabytes: parseInt(hubInfo.max_file_upload_size_megabytes),
      server: hubUrl
    };

    userData.gaiaHubConfig = hubConfig;
  }
  else if (associationToken) {
    userData.associationToken = associationToken;
  }

  const sessionData = userSession.store.getSessionData();
  sessionData.userData = userData;
  userSession.store.setSessionData(sessionData);

  const storage = new Storage({ userSession });
  return storage;
}

// Stores a list of files
async function putFiles(argv) {
  const opts = getCLIOpts(argv, "a:k:h:psg:", {
    "a": "association-token",
    "g": "gaia-auth",
    "k": "privkey",
    "h": "hub",
    "p": "no-encrypt",
    "s": "no-sign"
  });

  if (opts['k'] === null && opts['g'] === null) {
    usagePutFiles();
  }
  if (opts['h'] === null) {
    opts['h'] = DEFAULT_HUB;
  }

  const associationToken = opts['a'];
  const gaiaAuthToken = opts['g'];
  const privateKey = getPrivateKey(opts['k']);
  const hubUrl = opts['h'];
  const encrypt = !opts['p'];
  const sign = !opts['s'];
  const fileNamesAndPaths = opts['_'];

  if (fileNamesAndPaths.length % 2 !== 0) {
    usagePutFiles();
  }

  let uploads = [];
  for (let i = 0; i < fileNamesAndPaths.length / 2; i++) {
    const name = fileNamesAndPaths[2*i];
    const path = fileNamesAndPaths[2*i+1];
    uploads.push({
      name: name,
      path: path
    });
  }

  const storage = await makeStorage(privateKey, hubUrl, associationToken, gaiaAuthToken);
  const putFileOpts = {
    encrypt: encrypt,
    sign: sign
  };
  
  let urls = [];
  for(const upload of uploads) {
    const fileName = upload.name;
    const filePath = upload.path;

    const fileData = fs.readFileSync(filePath, { flag: 'r' });
    const fileUrl = await storage.putFile(fileName, fileData, putFileOpts);
    urls.push({
      name: fileName,
      url: fileUrl
    })
  }

  return urls;
}

// Lists files
async function listFiles(argv) {
  const opts = getCLIOpts(argv, "a:k:h:g:", {
    "a": "association-token",
    "g": "gaia-auth",
    "k": "privkey",
    "h": "hub",
  });
  
  if (opts['k'] === null && opts['g'] === null) {
    usageListFiles();
  }
  if (opts['h'] === null) {
    opts['h'] = DEFAULT_HUB;
  }

  const associationToken = opts['a'];
  const gaiaAuthToken = opts['g'];
  const privateKey = getPrivateKey(opts['k']);
  const hubUrl = opts['h'];
  
  const storage = await makeStorage(privateKey, hubUrl, associationToken, gaiaAuthToken);

  let names = [];
  await storage.listFiles((filename) => {
    names.push(filename);
    return true;
  });

  const res = {
    "names": names
  };

  return res;
}

// Delete files
async function deleteFiles(argv) {
  const opts = getCLIOpts(argv, "a:k:h:g:", {
    "a": "association-token",
    "g": "gaia-auth",
    "k": "privkey",
    "h": "hub",
  });
  
  if (opts['k'] === null && opts['g'] === null) {
    usageDeleteFiles();
  }
  if (opts['h'] === null) {
    opts['h'] = DEFAULT_HUB;
  }

  const associationToken = opts['a'];
  const gaiaAuthToken = opts['g'];
  const privateKey = getPrivateKey(opts['k']);
  const hubUrl = opts['h'];
  const names = opts['_'];
  
  const storage = await makeStorage(privateKey, hubUrl, associationToken, gaiaAuthToken);

  for (const name of names) {
    try {
      await storage.deleteFile(name, { wasSigned: true });
    }
    catch(e) {
      const hubError = e.hubError;
      if (hubError !== undefined) {
        if (hubError.statusCode === 404) {
          // absorb "Not found"
          continue;
        }
      }
      throw e;
    }
  }

  const res = {
    "names": names
  };

  return res;
}

// Inner get files
async function innerGetFiles(argv, names_and_paths, quiet, getFileOpts, getFileFunc, usage) {
  if (names_and_paths.length % 2 != 0) {
    usageGetFiles(argv);
  }

  let names = [];
  let paths = [];
  let haveStdin = false;
  for (let i = 0; i < names_and_paths.length; i += 2) {
    const name = names_and_paths[i];
    const path = names_and_paths[i+1];
    if (path === '-') {
      if (haveStdin) {
        usage(argv);
      }
      haveStdin = true;
    }
    names.push(name);
    paths.push(path);
  }

  if (haveStdin) {
    // default to quiet so we don't corrupt the stdout stream
    quiet = true;
  }

  let received = [];
  let received_paths = [];

  for(let i = 0; i < names.length; i++) {
    const name = names[i];
    const path = paths[i];
    const data = await getFileFunc(name, getFileOpts)
    if (data === undefined) {
      continue;
    }

    if (path == '-') {
      // send to stdout
      if (data instanceof ArrayBuffer) {
        fs.writeFileSync(1, Buffer.from(new Uint8Array(data)));
      }
      else {
        fs.writeFileSync(1, data);
      }
    }
    else {
      // store to path
      const dirname = Path.dirname(path);
      if (!fs.statSync(dirname)) {
        fs.mkdirSync(dirname, { recursive: true });
      }

      fs.writeFileSync(path, data);
    }

    received.push(name);
    received_paths.push(path);
  }

  if (quiet) {
    // print nothing
    return undefined;
  }

  let inner = [];
  for (let i = 0; i < received.length; i++) {
    inner.push({
      "name": received[i],
      "path": received_paths[i],
    });
  }

  const res = {
    received: inner
  };

  return res;
}

// Get files
async function getFiles(argv) {
  const opts = getCLIOpts(argv, "k:h:psq", {
    "k": "privkey",
    "h": "hub",
    "p": "not-encrypted",
    "s": "not-signed",
    "q": "quiet"
  });

  if (opts['h'] === null) {
    opts['h'] = DEFAULT_HUB;
  }

  const privateKey = getPrivateKey(opts['k']);
  const hubUrl = opts['h'];
  const decrypt = !opts['p'];
  const verify = !opts['s'];
  const quiet = opts['q'];

  const names_and_paths = opts['_'];
  
  const storage = await makeStorage(privateKey, hubUrl, undefined, undefined);
  const getFileOpts = {
    decrypt: decrypt,
    verify: verify,
    storage: storage
  };
  const getFileFunc = async function(name, opts) {
    const storage = opts.storage;
    try {
      const content = storage.getFile(name, opts);
      return content;
    }
    catch (error) {
      console.error(error);
      return undefined;
    }
  };

  const content = await innerGetFiles(argv, names_and_paths, quiet, getFileOpts, getFileFunc, usageGetFiles); 
  return content;
}

// Call a read-only function 
async function readOnlyContractCall(node, contract_addr, contract_name, function_name, function_args, mainnet) {
  const url = `${node}/v2/contracts/call-read/${contract_addr}/${contract_name}/${function_name}`;
  const body = {
    sender: getBurnAddress(mainnet),
    arguments: function_args.map(function(arg) {
      return stx.serializeCV(arg).toString('hex')
    })
  };

  let res;
  let data;

  try {
    res = await fetch(url, {
      method: 'post',
      body: JSON.stringify(body),
      headers: { 'content-type': 'application/json' }
    });
  }
  catch(error) {
    console.error(error);
    return undefined;
  }

  try {
    data = await res.json();
  }
  catch(error) {
    console.error(error);
    return undefined;
  }

  const encodedCV = data.result;
  return stx.deserializeCV(encodedCV);
}

// Resolve a name to its owner address and zone file hash
async function resolveName(bnsName, node, mainnet) {
  if (bnsName.indexOf(".") < 0) {
    const res = {
      "error": "Invalid BNS name: no '.'",
    };
    return res;
  }
  const parts = bnsName.split(".");
  if (parts.length !== 2) {
    const res = {
      "error": "Invalid BNS name: too many '.'",
    };
    return res;
  }
  const name = parts[0];
  const namespace = parts[1];

  const args = [
    stx.bufferCV(Buffer.from(namespace)),
    stx.bufferCV(Buffer.from(name))
  ];
  let res = await readOnlyContractCall(node, getBurnAddress(mainnet), "bns", "name-resolve", args, mainnet);
  if (res === undefined) {
    res = {
      "error": "Unable to contract Stacks node",
    };
    return res;
  }

  res = stx.cvToJSON(res);

  if (res["success"]) {
    res = {
      "lease_ending_at": res.value.value['lease-ending-at'].value.value,
      "lease_started_at": res.value.value['lease-started-at'].value,
      "owner": res.value.value['owner'].value,
      "zonefile_hash": res.value.value['zonefile-hash'].value.slice(2)
    }
  }
  else {
    res = {
      "error": "Failed to resolve BNS name",
      "code": parseInt(res.value.value)
    }
  }
  return res;
}

// Get the zone file for a BNS name
async function getNameZonefile(bnsName, node, mainnet, nameProps) {
  if (!nameProps) {
    const props = await resolveName(bnsName, node, mainnet);
    if (props.error) {
      return props;
    }
    nameProps = props;
  }

  const zonefileUrl = `${node}/v2/attachments/${nameProps.zonefile_hash}`;
  
  let zonefileHexData;
  try {
    const res = await fetch(zonefileUrl);
    zonefileHexData = await res.json();
  }
  catch (error) {
    console.error(error);
    return undefined;
  }

  let zonefileData;
  try {
    zonefileData = Buffer.from(zonefileHexData, 'hex')
  }
  catch (error) {
    console.error(error);
    return undefined;
  }

  return zonefileData;
}

// Get the profile by way of obtaining the zone file from the given node
async function getNameProfile(bnsName, node, mainnet) {
  const props = await resolveName(bnsName, node, mainnet);
  if (props.error) {
    return props;
  }
  const zonefileDataBin = await getNameZonefile(bnsName, node, mainnet, props);
  if (zonefileDataBin === undefined) {
    const ret = {
      'error': 'Failed to obtain zonefile for BNS name'
    };
    return ret;
  }

  let zonefileData;
  try {
    zonefileData = zonefileDataBin.toString('utf8');
  }
  catch (error) {
    console.error(error);
    return undefined;
  }

  let profile;
  try {
    profile = await stacksProfile.resolveZoneFileToProfile(zonefileData, props.owner, fetch);
  }
  catch (error) {
    console.error(error);
    return undefined;
  }

  const rec = {
    "name": props,
    "zonefileData": zonefileData,
    "profile": profile
  }
  return rec;
}

// Get the URL to a file, given a profile
function getFileURL(profile, appOrigin, filename) {
  let bucketUrl = undefined;
  if (profile.hasOwnProperty('apps')) {
    if (profile.apps.hasOwnProperty(appOrigin)) {
      const url = profile.apps[appOrigin];
      const bucket = url.replace(/\/?(\?|#|$)/, '/$1');
      bucketUrl = `${bucket}${filename}`;
    }
  }
  return bucketUrl
}

// Go get a public file
async function getPublicFileData(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`getFile ${url} failed`);
  }
  let contentType = response.headers.get('Content-Type');
  if (typeof contentType === 'string') {
    contentType = contentType.toLowerCase();
  }
  if (
    contentType === null ||
    contentType.startsWith('text') ||
    contentType.startsWith('application/json')
  ) {
    return response.text();
  } else {
    return response.arrayBuffer();
  }
}

// Decrypt an unsigned file
async function decryptFile(fileData, privateKey) {
  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  userSession.store.getSessionData().userData = {
    appPrivateKey: privateKey,
  };

  if (typeof privateKey === 'string') {
    const decryptOpt = { privateKey };
    const content = await userSession.decryptContent(fileData, decryptOpt);
    return content;
  } else {
    const content = await userSession.decryptContent(fileData);
    return content;
  }
}

// Decrypt a signed file
async function decryptSignedFile(fileData, privateKey, ownerAddress) {
  let sigObject;
  try {
    sigObject = JSON.parse(fileData);
  } catch (err) {
    if (err instanceof SyntaxError) {
      throw new Error(
        'Failed to parse signature content JSON '
      );
    } else {
      throw err;
    }
  }

  const signature = sigObject.signature;
  const signerPublicKey = sigObject.publicKey;
  const cipherText = sigObject.cipherText;
  const signerAddress = stacksEncryption.publicKeyToAddress(signerPublicKey);

  const appConfig = new AppConfig();
  const userSession = new UserSession({ appConfig });
  userSession.store.getSessionData().userData = {
    appPrivateKey: privateKey,
  };

  if (!signerPublicKey || !cipherText || !signature) {
    throw new Error(
      'Failed to get signature verification data from file:' + ` ${path}`
    );
  } else if (signerAddress !== ownerAddress) {
    throw new Error(
      `Signer pubkey address (${signerAddress}) doesn't match gaia address (${ownerAddress})`
    );
  } else if (!stacksEncryption.verifyECDSA(cipherText, signerPublicKey, signature)) {
    throw new SignatureVerificationError(
      `Contents do not match ECDSA signature in file: ${path}`
    );
  } else if (typeof privateKey === 'string') {
    const decryptOpt = { privateKey };
    const content = await userSession.decryptContent(cipherText, decryptOpt);
    return content;
  } else {
    const content = userSession.decryptContent(cipherText);
    return content;
  }
}

// Verify a signed file with a separate sigFile.
// Not necessary for encrypted+signed files
async function verifyFile(fileData, sigFile, ownerAddress) {
    let signature;
    let publicKey;
    try {
      const sigObject = JSON.parse(sigFile);
      signature = sigObject.signature;
      publicKey = sigObject.publicKey;
    } catch (err) {
      if (err instanceof SyntaxError) {
        throw new Error(
          'Failed to parse signature content JSON ' +
            `(path: ${path}${SIGNATURE_FILE_SUFFIX})` +
            ' The content may be corrupted.'
        );
      } else {
        throw err;
      }
    }
    const signerAddress = stacksEncryption.publicKeyToAddress(publicKey);
    if (ownerAddress !== signerAddress) {
      throw new Error(
        `Signer pubkey address (${signerAddress}) doesn't` +
          ` match owner address (${ownerAddress})`
      );
    } else if (!stacksEncryption.verifyECDSA(fileData, publicKey, signature)) {
      throw new Error(
        'Contents do not match ECDSA signature'
      );
    } else {
      return true;
    }
}

// Decrypt and/or verify a file.
// * if decrypt is true, then privateKey is necessary
// * if verify is true, then ownerAddress is necessary
// Retuns the content on success.
// Throws on error.
async function decodeFileData(fileData, sigData, privateKey, ownerAddress, decrypt, verify) {
  if (verify && decrypt) {
    if (!privateKey || !ownerAddress) {
      throw new Error("Need privateKey and ownerAddress");
    }
    const content = await decryptSignedFile(fileData, privateKey, ownerAddress);
    return content;
  }
  else if (verify && !decrypt) {
    if (!privateKey) {
      throw new Error("Need privateKey");
    }
    if (!sigData) {
      throw new Error("Need signature file");
    }
    if (!verifyFile(fileData, sigData, ownerAddress)) {
      throw new Error(`Verification error: failed to verify ${fileUrl} with ${ownerAddress}`);
    }
    return fileData;
  }
  else if (!verify && decrypt) {
    if (!ownerAddress) {
      throw new Error("Need ownerAddress");
    }
    const content = await decryptFile(fileData, privateKey);
    return content;
  }
  else {
    return fileData;
  }
}

// Go get a public file, and decrypt and/or verify it.
// * if decrypt is true, then privateKey is necessary
// * if verify is true, then ownerAddress is necessary
// Returns the content (not undefined) on success.
// Returns undefined on error.
async function getAndDecodePublicFile(fileUrl, privateKey, ownerAddress, decrypt, verify) {
  let fileData = undefined;
  let sigData = undefined;
  let content = undefined;
  try {
    fileData = await getPublicFileData(fileUrl);
  }
  catch (error) {
    console.error("Failed to fetch file");
    console.error(e);
    return undefined;
  }

  if (verify && !decrypt) {
    try {
      sigData = await getPublicFileData(`${fileUrl}.sig`);
    }
    catch (error) {
    console.error("Failed to fetch sigfile");
      console.error(e);
      return undefined;
    }
  }

  try {
    content = await decodeFileData(fileData, sigData, privateKey, ownerAddress, decrypt, verify);
  }
  catch (error) {
    console.error(e);
    return undefined;
  }

  return content;
}

// Get public files
async function getPublicFiles(argv) {
  const opts = getCLIOpts(argv, "a:b:n:k:psqt", {
    "b": "bns-name",
    "a": "app-url",
    "k": "privkey",
    "n": "node",
    "p": "not-encrypted",
    "s": "not-signed",
    "q": "quiet",
    "t": "testnet"
  });

  if (opts['b'] === null) {
    console.error("Missing -b");
    usageGetPublicFiles();
  }

  if (opts['a'] === null) {
    console.error("Missing -a");
    usageGetPublicFiles();
  }

  if (opts['n'] === null) {
    opts['n'] = DEFAULT_NODE;
  }

  const username = opts['b'];
  const app_url = opts['a'];
  const decrypt = !opts['p'];
  const verify = !opts['s'];
  const node = opts['n'];
  const quiet = opts['q'];
  const privateKey = getPrivateKey(opts['k']);
  const mainnet = !opts['t']

  const names_and_paths = opts['_'];

  const profile = await getNameProfile(username, node, mainnet);
  if (!profile) {
    const ret = {
      'error': 'Failed to get name profile'
    };
    return ret;
  }

  const getFileOpts = {
    username: username,
    app: app_url,
    decrypt: decrypt,
    verify: verify,
    profile: profile,
    privateKey: privateKey,
  };
  const getFileFunc = async function(name, opts) {
    const fileUrl = getFileUrl(opts.profile, opts.app, name);
    if (!fileUrl) {
      return undefined;
    }
    const ownerAddress = opts.profile.name.owner;
    const privateKey = opts.privateKey;
    try {
      const content = await getAndDecodePublicFile(fileUrl, privateKey, ownerAddress, decrypt, verify);
      return content;
    }
    catch (error) {
      console.error(error);
      return undefined;
    }
  };
  const content = await innerGetFiles(argv, names_and_paths, quiet, getFileOpts, getFileFunc, usageGetPublicFiles); 
  return content;
}

// Get someone's BNS name info, zonefile, and profile
async function getProfiles(argv) {
  const opts = getCLIOpts(argv, "n:t", {
    "n": "node",
    "t": "testnet"
  });

  if (opts['n'] === null) {
    opts['n'] = DEFAULT_NODE;
  }
  const mainnet = !opts['t'];
  const node = opts['n'];

  if (opts['_'].length === 0) {
    usageGetProfiles();
  }

  const names = opts['_'];
  let ret = [];
  for (let name of names) {
    try {
      const profile = await getNameProfile(name, node, mainnet);
      ret.push(profile);
    }
    catch (error) {
      console.error(error);
      ret.push({'error': 'Failed to load profile'});
    }
  }
  return ret;
}

// Get someone's BNS zone file, optionally dumping it directly to stdout
async function getZonefiles(argv) {
  const opts = getCLIOpts(argv, "n:tr", {
    "n": "node",
    "t": "testnet",
    "r": "raw"
  });

  if (opts['n'] === null) {
    opts['n'] = DEFAULT_NODE;
  }
  const mainnet = !opts['t'];
  const node = opts['n'];
  const raw = opts['r'];

  if (opts['_'].length === 0) {
    usageGetZonefiles();
  }
  const names = opts['_'];

  let ret = [];
  for (let name of names) {
    try {
      const zonefileRaw = await getNameZonefile(name, node, mainnet);
      if (raw) {
        // send to stdout
        if (zonefileRaw instanceof ArrayBuffer) {
          fs.writeFileSync(1, Buffer.from(new Uint8Array(zonefileRaw)));
        }
        else {
          fs.writeFileSync(1, zonefileRaw);
        }
      }
      else {
        let zonefileData;
        try {
          zonefileData = zonefileRaw.toString('utf8');
          ret.push(zonefileData);
        }
        catch (error) {
          console.error(error);
          ret.push({'error': 'Failed to decode zone file'});
        }
      }
    }
    catch (error) {
      console.error(error);
    }
  }

  if (raw) {
    return undefined;
  }
  else {
    return ret;
  }
}

// Get someone's BNS name record
async function getNameRecords(argv) {
  const opts = getCLIOpts(argv, "n:tr", {
    "n": "node",
    "t": "testnet",
  });

  if (opts['n'] === null) {
    opts['n'] = DEFAULT_NODE;
  }
  const mainnet = !opts['t'];
  const node = opts['n'];
  const raw = opts['r'];

  if (opts['_'].length === 0) {
    usageGetZonefiles();
  }
  const names = opts['_'];

  let ret = [];
  for (let name of names) {
    try {
      const namerec = await resolveName(name, node, mainnet);
      ret.push({
        "name": name,
        "record": namerec
      });
    }
    catch (error) {
      console.error(error);
    }
  }

  return ret;
}

// Decode a Gaia-stored file
async function decodeFile(argv) {
  const opts = getCLIOpts(argv, "k:o:ps", {
    "k": "privkey",
    "o": "owner",
    "p": "not-encrypted",
    "s": "not-signed"
  });
  
  const decrypt = !opts['p'];
  const verify = !opts['s'];
  const ownerAddress = opts['o'];
  const privateKey = getPrivateKey(opts['k']);
  const fileDatas = opts['_'];

  if (fileDatas.length < 1) {
    usageDecodeFile();
  }

  if (!decrypt && verify && fileDatas.length < 2) {
    usageDecodeFile();
  }

  const filePath = fileDatas[0];
  const sigPath = fileDatas.length > 1 ? fileDatas[1] : undefined;

  const fileData = fs.readFileSync(filePath, { flag: 'r' });
  const sigData = !!sigPath ? fs.readFileSync(sigPath, { flags: 'r' }).toString() : undefined;

  const decodedData = await decodeFileData(fileData, sigData, privateKey, ownerAddress, decrypt, verify);
  if (decodedData instanceof ArrayBuffer) {
    fs.writeFileSync(1, Buffer.from(new Uint8Array(decodedData)));
  }
  else {
    fs.writeFileSync(1, decodedData);
  }
  return undefined;
}

function doHelp(subcommand) {
  if (subcommand === "putfiles") {
    usagePutFiles();
  }
  else if (subcommand === "listfiles") {
    usageListFiles();
  }
  else if (subcommand === "deletefiles") {
    usageDeleteFiles();
  }
  else if (subcommand === "getfiles") {
    usageGetFiles();
  }
  else if (subcommand === "getpubfiles") {
    usageGetPublicFiles();
  }
  else if (subcommand === "getprofiles") {
    usageGetProfiles();
  }
  else if (subcommand === "getzonefiles") {
    usageGetZonefiles();
  }
  else {
    usageSubcommands();
  }
}

async function main() {
  const argv = process.argv.slice(1);
  const subcommand = argv[1];
  if (subcommand === "putfiles") {
    const res = await putFiles(argv.slice(2));
    console.log(JSON.stringify(res));
  }
  else if (subcommand === "listfiles") {
    const res = await listFiles(argv.slice(2));
    console.log(JSON.stringify(res));
  }
  else if (subcommand === "deletefiles") {
    const res = await deleteFiles(argv.slice(2));
    console.log(JSON.stringify(res));
  }
  else if (subcommand === "getfiles") {
    const res = await getFiles(argv.slice(2));
    if (res !== undefined) {
      console.log(JSON.stringify(res));
    }
  }
  else if (subcommand === "getpubfiles") {
    const res = await getPublicFiles(argv.slice(2));
    if (res !== undefined) {
      console.log(JSON.stringify(res));
    }
  }
  else if (subcommand === "getprofiles") {
    const res = await getProfiles(argv.slice(2));
    if (res !== undefined) {
      console.log(JSON.stringify(res));
    }
  }
  else if (subcommand === "getzonefiles") {
    const res = await getZonefiles(argv.slice(2));
    if (res !== undefined) {
      console.log(JSON.stringify(res));
    }
  }
  else if (subcommand === "getnames") {
    const res = await getNameRecords(argv.slice(2));
    if (res !== undefined) {
      console.log(JSON.stringify(res));
    }
  }
  else if (subcommand === "decodefile") {
    const res = await decodeFile(argv.slice(2));
    if (res !== undefined) {
      console.log(JSON.stringify(res));
    }
  }
  else if (subcommand === "help") {
    doHelp(argv[3]);
  }
  else {
    doHelp(argv[2]);
  }
}

main()
